repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black (line-length=100)
        args: ["--line-length", "100"]
        language_version: python3
        files: \.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (profile=black)
        args: ["--profile", "black"]
        language_version: python3
        files: \.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8 (max-line-length=100, ignore=E501)
        args:
          - "--max-line-length=100"
          - "--ignore=E501"
        language_version: python3
        files: \.py$
